spring:
  application:
    name: faturacao

  data:
    web:
      pageable:
        max-page-size: 100

  datasource:
    url: jdbc:postgresql://localhost:5433/faturacao
    username: faturacao
    password: faturacao

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  flyway:
    enabled: true
