CREATE TABLE clients (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    nif          VARCHAR(9)   NOT NULL,
    email        VARCHAR(255),
    phone        VARCHAR(20),
    address      VARCHAR(255),
    postal_code  VARCHAR(8),
    city         VARCHAR(100),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_clients_nif UNIQUE (nif)
);