CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(30)    NOT NULL,
    name         VARCHAR(150)   NOT NULL,
    description  VARCHAR(500),
    type         VARCHAR(10)    NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    vat_rate     VARCHAR(20)    NOT NULL,
    active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uk_products_code       UNIQUE (code),
    CONSTRAINT ck_products_type       CHECK (type IN ('PRODUCT', 'SERVICE')),
    CONSTRAINT ck_products_vat_rate   CHECK (vat_rate IN ('NORMAL', 'INTERMEDIATE', 'REDUCED')),
    CONSTRAINT ck_products_unit_price CHECK (unit_price >= 0)
);