CREATE TABLE invoices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT         NOT NULL,
    status      VARCHAR(20)    NOT NULL,
    due_date    DATE           NOT NULL,
    notes       VARCHAR(500),
    total_net   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_vat   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT fk_invoices_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT ck_invoices_status CHECK (status IN ('DRAFT', 'ISSUED', 'PAID', 'CANCELLED'))
);

CREATE INDEX idx_invoices_client ON invoices (client_id);
CREATE INDEX idx_invoices_status ON invoices (status);

CREATE TABLE invoice_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT         NOT NULL,
    line_number     INT            NOT NULL,
    product_id      BIGINT         NOT NULL,
    product_code    VARCHAR(30)    NOT NULL,
    description     VARCHAR(150)   NOT NULL,
    quantity        NUMERIC(10, 3) NOT NULL,
    unit_price      NUMERIC(12, 2) NOT NULL,
    vat_rate        VARCHAR(20)    NOT NULL,
    vat_percentage  NUMERIC(5, 2)  NOT NULL,
    line_net        NUMERIC(12, 2) NOT NULL,
    line_vat        NUMERIC(12, 2) NOT NULL,
    line_total      NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_invoice_lines_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_lines_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_invoice_lines_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_invoice_lines_invoice ON invoice_lines (invoice_id);