-- Contador de números por série e ano (ex: FT / 2026 / último número usado)
CREATE TABLE invoice_series (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix       VARCHAR(10) NOT NULL,
    fiscal_year  INT         NOT NULL,
    last_number  INT         NOT NULL DEFAULT 0,
    CONSTRAINT uk_invoice_series UNIQUE (prefix, fiscal_year)
);

-- Dados de emissão, pagamento e anulação
ALTER TABLE invoices
    ADD COLUMN version              BIGINT       NOT NULL DEFAULT 0,
    ADD COLUMN series_prefix        VARCHAR(10),
    ADD COLUMN fiscal_year          INT,
    ADD COLUMN sequence_number      INT,
    ADD COLUMN number               VARCHAR(30),
    ADD COLUMN issue_date           DATE,
    ADD COLUMN paid_date            DATE,
    ADD COLUMN cancelled_at         TIMESTAMPTZ,
    ADD COLUMN cancellation_reason  VARCHAR(255),
    -- Fotografia do cliente no momento da emissão
    ADD COLUMN client_name          VARCHAR(150),
    ADD COLUMN client_nif           VARCHAR(9),
    ADD COLUMN client_address       VARCHAR(255),
    ADD COLUMN client_postal_code   VARCHAR(8),
    ADD COLUMN client_city          VARCHAR(100);

ALTER TABLE invoices
    ADD CONSTRAINT uk_invoices_series_number UNIQUE (series_prefix, fiscal_year, sequence_number),
    ADD CONSTRAINT uk_invoices_number UNIQUE (number),
    ADD CONSTRAINT ck_invoices_issued_has_number
        CHECK (status = 'DRAFT' OR (number IS NOT NULL AND issue_date IS NOT NULL));