CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    supplier_name VARCHAR(150),
    supplier_nif VARCHAR(9),
    expense_date DATE NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    vat_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    net_amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_expenses_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_expenses_total CHECK (total_amount > 0),
    CONSTRAINT ck_expenses_vat CHECK (
        vat_amount >= 0
        AND vat_amount <= total_amount
    ),
    CONSTRAINT ck_expenses_net CHECK (net_amount = total_amount - vat_amount),
    CONSTRAINT ck_expenses_payment_method CHECK (
        payment_method IN ('CARD', 'CASH', 'TRANSFER', 'MB_WAY', 'OTHER')
    )
);

CREATE INDEX idx_expenses_category ON expenses (category_id);

CREATE INDEX idx_expenses_date ON expenses (expense_date);